### PR TITLE
Rsbranch

### PR DESCRIPTION
**Pull request by rustonray**
# Description
I have created the register function for the app so that new users can register their profile. This coincides with the #29 trello ticket https://trello.com/c/dsizqWLn/29-29-register

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions
STEPS TO TEST
1. After making sure you have our repo cloned down into a local repository and have the database added, git fetch --all in the master branch to retrieve the branch named rsbranch that I have pushed up.
2. Git checkout rsbranch to switch to my branch and open up the project (TabloidMVC) in Visual Studio.
3. Then, run the application in a browser window. 
4. You should see the 'Home' page with a navigation bar at the top of the page. If not already logged out, log out (with the link in the navbar).
5. Then, click the register button under the login button.
6. When promted to register a new user, please enter Bill in the first name tab
7. Please enter Clinton in the last name tab
8. Enter BillClinton in the screen name tab, 
9. Enter BillClinton@gmail. com in the email tab. 
10. Once all the values are filled in, click submit.
11. After you submit the values, In visual studio run the database in the SQL Object explorer, you do this by typing "select * from UserProfile"
12.  Check to see if the values you submitted for the register function are recorded in the database.
13. If they are, the register function is working succesfully and you are good to go.
14. If they aren't, give up and cry.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Our tests need to look like the gist. So move your testing instructions from description down into the testing instructions. Please remove the delete options not relevant from type of change

Our testing results need to be really through and easily legible so make more steps in smaller sizes 

Give explicit instructions so - register with this email, this first name, this last name

Make sure to give them the exact SQL query they need to see if register is working correctly.

**Review by sarahebrooks12 — APPROVED** [review]
Looks good 👼🏻

**Comment by fwee1996** [comment]
Looks good to me

**Comment by tylerhamilton888** [comment]
Working for me

**Pull request merged**
