### PR TITLE
Tyler edit posts1

### PR DESCRIPTION
**Pull request by tylerhamilton888**
# Description

Added the ability for a user to edit their posts.  Users can navigate to a post they have authored, hit the "edit" button, and they will be directed to a page that allows them to edit any feature of their post.

Fulfills Trello ticket #8, "Edit a Post" https://trello.com/c/1CO8NmNn/8-8-edit-a-post

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. Clone down the repository
2. git checkout main
3. git fetch --all
4. git checkout tyler-edit-posts1
5. If you don't see the most recent version of my files, git pull origin tyler-edit-posts1
6. Open the project (TabloidMVC) in Visual Studio
7. If you haven't already, create a database called "TabloidMVC." The data we are using can be found under the "SQL" folder when looking at our group repository. Be sure to run a query for both files (Create_DB and Seed_Data)
8. Start the server. It should automatically open a webpage on your browser.
9. You'll be greeted by a page that will say "Blogs & Journals", "Get Started", and "Login." Click on Login
11. Login using admin@example.com and hit "Submit"
12. Using the navbar at the top, navigate to "Posts"
13. Click on "New Posts"
14. Fill out all of the boxes as outlined in the following steps
15.  Title- Testing
16. Header Image URL-https://upload.wikimedia.org/wikipedia/commons/6/6e/Golde33443.jpg
17.  Published- click on today's date on the calendar
18.  Category- Technology
19.  Content- This is a test post
20. Click "Save" to create your new post
21. You should see a page for your new post.
22. EITHER click the blue pencil "Edit" on your post page OR navigate back to posts and click the edit icon next to your new post.
23. You will be directed to an edit page that will allow you to edit any or all of the features of your post.
24. Click "Back to List" and verify it returns you to the list of posts without having edited your post.
25. Click on the pencil (edit) icon by your post again. You can either do this from the list of posts, or from the details page about your post.
26. You will be directed to your edit page again
27. IMPORTANT- WHEN EDITING A POST, ENSURE YOU CHECK THE "Approved" BOX.  YOUR POST WILL DISAPPEAR FROM THE LIST IF YOU DO NOT.  It will still exist, but in order to re-access it you will have to manually navigate to the URL.
28. Edit the post title to be "QA Testing"
29. Click save.
30. Go to your post details and verify that they have been changed with your edit.
31. Congratulations, you have edited a post.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by fwee1996** [comment]
Works for me

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Please have the tester create a new post to edit instead of editing our seed data. We want to protect our data. 

So it'd be like:
Create a post:
Title: Testing
Content: Testing PR

Then go the post with the title Testing and edit it to QA Testing. 

Then continue with those steps

**Review by sarahebrooks12 — APPROVED** [review]
Looks good

**Comment by rustonray** [comment]
looks good!!

**Pull request merged**
